---
apiVersion: v1
kind: Service
metadata:
  name: ft-demo
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
  selector:
    app: ft-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ft-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft-demo
  template:
    metadata:
      labels:
        app: ft-demo
    spec:
      containers:
        - name: ft-demo
          image: i349272/ft-demo:1.2
          env:
            - name: HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: hostname
                  key: HOSTNAME
          ports:
            - containerPort: 5000
